# Generated by Django 2.2.17 on 2021-03-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210331_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
