bedroom_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
}

price_choices = {
    '10000':'$10,000',
    '20000':'$20,000',
    '30000':'$30,000',
    '40000':'$40,000',
    '50000':'$50,000',
    '60000':'$60,000',
    '70000':'$70,000',
    '80000':'$80,000',
    '90000':'$90,000',
    '100000':'$1 M+'
}

state_choices = {
    "AK":'Alaska',
    "AL":'Alabama',
    "AZ":'Arizona',
    "AR":'Arkansas',
    "CA":'California',
    "CO":'Colorado',
    "CT":'Connecticut',
    "DE":'Delaware',
    "DC":'District Of Columbia',
    "FL":'Florida',
    "GA":'Georgia',
    "HI":'Hawaii',
    "ID":'Idaho',
    "IL":'Illinois',
    "IN":'Indiana',
    "IA":'Iowa',
    "KS":'Kansas',
    "KY":'Kentucky',
    "LA":'Louisiana',
    "ME":'Maine',
    "MD":'Maryland',
    "MA":'Massachusetts',
    "MI":'Michigan',
    "MN":'Minnesota',
    "MS":'Mississippi',
    "MO":'Missouri',
    "MT":'Montana',
    "NE":'Nebraska',
    "NV":'Nevada',
    "NH":'New Hampshire',
    "NJ":'New Jersey',
    "NM":'New Mexico',
    "NY":'New York',
    "NC":'North Carolina',
    "ND":'North Dakota',
    "OH":'Ohio',
    "OK":'Oklahoma',
    "OR":'Oregon',
    "PA":'Pennsylvania',
    "RI":'Rhode Island',
    "SC":'South Carolina',
    "SD":'South Dakota',
    "TN":'Tennessee',
    "TX":'Texas',
    "UT":'Utah',
    "VT":'Vermont',
    "VA":'Virginia',
    "WA":'Washington',
    "WV":'West Virginia',
    "WI":'Wisconsin',
    "WY":'Wyoming'
}